-- AlterTable
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "onlinePaymentEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "codPaymentEnabled" BOOLEAN NOT NULL DEFAULT true;
